### ISSUE TITLE
Problem creating cards

### ISSUE THREAD

**Issue by Boso101** [doombubbles/metastonething#2]
Hi, with your build of the game, I cannot seem to create new hero's or hero powers. I have a card exactly like Majordomo which changes the hero into another hero. But when this happens, I lose most of the functionanity in the game. The hero portrait and hero power do not change and all I can do is end my turn. 

These cards were added via the documents/metastone

**Comment by doombubbles** [comment]
The issue probably comes from how I changed the imaging system to work, it might give you errors if you tried to use a hero but didn't also add a new hero portrait icon and hero power icon in the source files to go with it. I thought I had it so that it would just use a default image if none was found, but apparently that doesn't seem to be working.

**Comment by Boso101** [comment]
alright, in that case where/how do I set the images for the hero portrait and icon?

**Comment by doombubbles** [comment]
https://github.com/doombubbles/metastonething/tree/master/app/src/main/resources/img heroes folder and powers folder in there, you'll see the format
